### ISSUE TITLE
Suggestion: Add link to report bug / stat changes on game-over screen

### ISSUE THREAD

**Issue by raymondgh** [devinwl/rubicktrainer#1]
Seems like a natural time and place for users to be ready to suggest or comment on the state of the app. If anything is wrong in app, they can suggest it be fixed easily. Maybe even add a contact form as well as link to github so the non-technical users can complain as well

**Comment by wonderfulfrog** [comment]
A link to the issue tracker for the repo has been added in b32f59e1c3cd76dbeb6d02fae166bcdf3eca01ae.  A general-use contact form may be added in the future.

Thanks for your suggestion!
